---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xn18kcl0/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -r css $DEPLOYPATH
    - /bin/cp -r assests $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
